### PR TITLE
Return of the prodigal THUMBNAIL_FORCE_OVERWRITE

### PR DESCRIPTION
**Pull request by haakenlid**
I couldn't find original commit (commit
eb569ad2a53e3ab402059aed151d0f3f1d2820fb) mentioned in issue #351.

The commit didn't seem to be part of any existing branch in the repo,
and it's gone from the master branch.

### CODE REVIEW

**Comment by haakenlid** [comment]
The Travis CI build process seems to be broken at the moment. 
I suspect it's because the .coveragerc file is no longer valid in the new version of coverage. http://coverage.readthedocs.org/en/coverage-4.0/changes.html

I've made a change to `.coveragerc` that I hope will make the tests run correctly with the new version. According to the docs, `exclude_lines` configuration like it should be part of the `[report]` block. (http://coverage.readthedocs.org/en/coverage-4.0/config.html#syntax)

**Comment by mariocesar** [comment]
@haakenlid thanks I didn't notice will do a double check and then merge it again

**Comment by mariocesar** [comment]
@haakenlid crap ... :( I made a huge mistake trying to revert a commit, never will do that again

**Comment by mariocesar** [comment]
@haakenlid Sorry for the confusions on merging, your changes are in master now

**Comment by haakenlid** [comment]
Cool. :+1:

**Pull request merged**
