### PR TITLE
PNG files haven't transparency.

### PR DESCRIPTION
**Pull request by caioariede**
Hi, how are you?

Here have a new issue, i think.

My png file haven't background color, have transparency, and, when i upload using sorl-thumbnail's ImageField the image have black background color, see:

sorl-thumbnailissue

How can we fix this bug?

### CODE REVIEW

**Comment by caioariede** [comment]
Please reopen if the bug persists

**Comment by matheusjardimb** [comment]
@caioariede sorry about the really late answer. I just upgraded sorl-thumbnail to 12.3 and it is still happening. I've tested it in my windows dev machine and I'll try it in my ubuntu server as well.

Did you expect to solve it only by upgrading the lib version or should I change something in my code too?

I just uploaded this random png image with transparency 
untitled

and the output was this

5bcf2740bade05e5391cb679170ab606

**Comment by matheusjardimb** [comment]
I've got it working by adding this https://gist.github.com/narrowfail/10e9f81fc32d6422b1b2 to my settings. But I'd still prefer a solution in the lib itself (instead of 'hacking')

**Comment by SalahAdDin** [comment]
:+1:

**Comment by matheusjardimb** [comment]
as a quick solution, you can also use

```
THUMBNAIL_PRESERVE_FORMAT = True
```

**Comment by caioariede** [comment]
@matheusjardimb what you are reporting now is not a bug, but the expected behavior.

Your image is being converted to JPEG due to the `THUMBNAIL_FORMAT` setting.

You can prevent this by setting `THUMBNAIL_FORMAT = 'PNG'` or `THUMBNAIL_PRESERVE_FORMAT = True`

ps: JPEG images does not support transparency.

**Pull request merged**
